[comments]
  # Comment provider:
    provider = "giscus"

  # Which page types are commentable?
    commentable = {page = false, post = true, docs = false, project = false, publication = true, talk = false}

  # Configuration of giscus
    [comments.giscus]
    repo = "oelnbod/blog-comments" # Repo where the comments will live
    repo_id = "R_kgDOOaBrXA" # Repo where the comments will live
    category = "Announcements" # Repo where the comments will live
    category_id = "DIC_kwDOOaBrXM4CpHvw" # Repo where the comments will live
    mapping = "pathname" # How Utterances will match comment to page
    label = "comment" # Label applied to issue by utteranc.es bot
    theme = "light" # What theme to use
    reactions_enabled = 1